# Generated by Django 3.1.4 on 2021-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500, unique=True)),
                ('Submission_Date', models.DateTimeField()),
                ('Is_scraped', models.CharField(choices=[], max_length=50)),
                ('Is_Phishing', models.BooleanField()),
            ],
        ),
    ]
