# Generated by Django 3.1.4 on 2021-02-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUrlDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500, unique=True)),
                ('Is_scraped', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('Faild', 'F')], max_length=50)),
                ('Is_Phishing', models.BooleanField()),
                ('Features', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='urlDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500, unique=True)),
                ('Submission_Date', models.DateTimeField()),
                ('Is_scraped', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('Faild', 'F')], max_length=50)),
                ('Is_Phishing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='webScraingDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500, unique=True)),
                ('Features', models.CharField(max_length=100)),
                ('Is_Phishing', models.BooleanField()),
                ('Is_Trained', models.BooleanField()),
                ('Is_From_Client', models.BooleanField()),
                ('urlId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urldb')),
            ],
        ),
    ]
