# Generated by Django 3.1.5 on 2021-02-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web_scraping_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Features', models.CharField(max_length=100)),
                ('Is_Phishing', models.BooleanField()),
                ('Is_Trained', models.BooleanField()),
                ('Is_From_Client', models.BooleanField()),
                ('urlId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urls')),
            ],
        ),
        migrations.CreateModel(
            name='Phishtank_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submission_Date', models.DateTimeField()),
                ('Is_scraped', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('Faild', 'F')], max_length=50)),
                ('URL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urls')),
            ],
        ),
        migrations.CreateModel(
            name='Client_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Phishing', models.BooleanField()),
                ('Features', models.CharField(max_length=100)),
                ('Submission_Count', models.IntegerField()),
                ('URL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urls')),
            ],
        ),
    ]
