# Generated by Django 3.1.5 on 2021-02-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Acquisition', '0002_auto_20210202_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_urls',
            name='URL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urls', unique=True),
        ),
        migrations.AlterField(
            model_name='web_scraping_data',
            name='urlId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urls', unique=True),
        ),
    ]
