# Generated by Django 3.1.5 on 2021-02-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Acquisition', '0003_auto_20210203_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_urls',
            old_name='Features',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='client_urls',
            old_name='Is_Phishing',
            new_name='is_phishing',
        ),
        migrations.RenameField(
            model_name='client_urls',
            old_name='Submission_Count',
            new_name='submission_count',
        ),
        migrations.RenameField(
            model_name='client_urls',
            old_name='URL_ID',
            new_name='url_id',
        ),
        migrations.RenameField(
            model_name='phishtank_urls',
            old_name='Is_scraped',
            new_name='is_scraped',
        ),
        migrations.RenameField(
            model_name='phishtank_urls',
            old_name='Submission_Date',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='phishtank_urls',
            old_name='URL_ID',
            new_name='url_id',
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='URL',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='web_scraping_data',
            old_name='Features',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='web_scraping_data',
            old_name='Is_From_Client',
            new_name='is_from_client',
        ),
        migrations.RenameField(
            model_name='web_scraping_data',
            old_name='Is_Phishing',
            new_name='is_phishing',
        ),
        migrations.RenameField(
            model_name='web_scraping_data',
            old_name='Is_Trained',
            new_name='is_trained',
        ),
        migrations.RenameField(
            model_name='web_scraping_data',
            old_name='urlId',
            new_name='url_id',
        ),
    ]
