# Generated by Django 3.1.5 on 2021-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Acquisition', '0004_auto_20210203_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_urls',
            name='is_in_web_scraping',
            field=models.BooleanField(default=False),
        ),
    ]
