# Generated by Django 3.1.5 on 2021-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Acquisition', '0005_client_urls_is_in_web_scraping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
