# Generated by Django 3.1.5 on 2021-03-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Acquisition', '0006_auto_20210215_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UIDS_URLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.uids')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_Acquisition.urls')),
            ],
        ),
    ]
