# Generated by Django 3.1.5 on 2021-03-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Acquisition', '0007_uids_uids_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uids',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
